/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.FerramentaDAO;
import Model.Ferramenta;
import static Utils.Utils.validarNome;
import static java.lang.Double.parseDouble;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme
 */
public class TelaCadastroFerramenta extends javax.swing.JFrame {

    private final FerramentaDAO objetoferramenta;

    public TelaCadastroFerramenta() {
        initComponents();
        this.objetoferramenta = new FerramentaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaCadastroDeFerramenta = new javax.swing.JPanel();
        txtNomeFerramenta = new javax.swing.JTextField();
        txtMarcaFerramenta = new javax.swing.JTextField();
        txtCustoFerramenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegFerramenta = new javax.swing.JButton();
        btnregferranentaVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaCadastroDeFerramenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Ferramentas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtMarcaFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaFerramentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Custo:");

        btnRegFerramenta.setText("Registrar");
        btnRegFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegFerramentaActionPerformed(evt);
            }
        });

        btnregferranentaVoltar.setText("Voltar");
        btnregferranentaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregferranentaVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaCadastroDeFerramentaLayout = new javax.swing.GroupLayout(TelaCadastroDeFerramenta);
        TelaCadastroDeFerramenta.setLayout(TelaCadastroDeFerramentaLayout);
        TelaCadastroDeFerramentaLayout.setHorizontalGroup(
            TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroDeFerramentaLayout.createSequentialGroup()
                .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaCadastroDeFerramentaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaCadastroDeFerramentaLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnregferranentaVoltar))
                            .addComponent(btnRegFerramenta)))
                    .addGroup(TelaCadastroDeFerramentaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMarcaFerramenta)
                            .addComponent(txtNomeFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TelaCadastroDeFerramentaLayout.createSequentialGroup()
                                .addComponent(txtCustoFerramenta)
                                .addGap(3, 3, 3)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        TelaCadastroDeFerramentaLayout.setVerticalGroup(
            TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroDeFerramentaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustoFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(TelaCadastroDeFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegFerramenta)
                    .addComponent(btnregferranentaVoltar))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaCadastroDeFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaCadastroDeFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegFerramentaActionPerformed
        try {

            String nome = "", marca = "";
            int id = 0;
            double custo = 0;

            nome = this.txtNomeFerramenta.getText().toLowerCase();
            marca = this.txtMarcaFerramenta.getText().toLowerCase();

            if (this.txtCustoFerramenta.getText().isEmpty()) {
                throw new MensagensException("O campo de custo deve ser preenchido");
            } else if (parseDouble(this.txtCustoFerramenta.getText()) == 0) {
                throw new MensagensException("O campo de custo não pode ser 0");
            }

            custo = parseDouble(this.txtCustoFerramenta.getText());

            if (nome.length() < 2 || !validarNome(nome)) {
                throw new MensagensException("Preencha um nome valido");
            }

            if (marca.length() < 3) {
                throw new MensagensException("Insira uma marca de ferramenta valida");
            }

            ArrayList<Ferramenta> listaFerramenta = objetoferramenta.getMinhaLista();

            for (Ferramenta ferramenta : listaFerramenta) {
                if (ferramenta.getNome().equals(nome) && ferramenta.getMarca().equals(marca)) {
                    throw new MensagensException("A ferramenta já está cadastrado.");
                }
            }

            this.objetoferramenta.InsertFerramentaBD(id, nome, marca, custo);

            this.txtNomeFerramenta.setText("");
            this.txtMarcaFerramenta.setText("");
            this.txtCustoFerramenta.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ferramenta cadastrada com sucesso");
            System.out.println(this.objetoferramenta.getMinhaLista().toString());

        } catch (MensagensException erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        } catch (SQLException erro) {
        }
    }//GEN-LAST:event_btnRegFerramentaActionPerformed

    private void txtMarcaFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaFerramentaActionPerformed

    private void btnregferranentaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregferranentaVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnregferranentaVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelaCadastroDeFerramenta;
    private javax.swing.JButton btnRegFerramenta;
    private javax.swing.JButton btnregferranentaVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCustoFerramenta;
    private javax.swing.JTextField txtMarcaFerramenta;
    private javax.swing.JTextField txtNomeFerramenta;
    // End of variables declaration//GEN-END:variables
}
