package View;

import DAO.AmigoDAO;
import Model.Amigo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme
 */
public class TelaCadastroAmigo extends javax.swing.JFrame {

    private final AmigoDAO objetoamigo;

    public TelaCadastroAmigo() {
        initComponents();
        this.objetoamigo = new AmigoDAO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaCadastroDeAmigo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txtNomeAmigo = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        B_Registrar = new javax.swing.JButton();
        B_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaCadastroDeAmigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Amigo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Insira os dados do amigo");

        Nome.setText("Nome:");

        Telefone.setText("Telefone:");

        Email.setText("Email:");

        txtNomeAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAmigoActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        B_Registrar.setText("Registrar");
        B_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistrarActionPerformed(evt);
            }
        });

        B_Voltar.setText("Voltar");
        B_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaCadastroDeAmigoLayout = new javax.swing.GroupLayout(TelaCadastroDeAmigo);
        TelaCadastroDeAmigo.setLayout(TelaCadastroDeAmigoLayout);
        TelaCadastroDeAmigoLayout.setHorizontalGroup(
            TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroDeAmigoLayout.createSequentialGroup()
                .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaCadastroDeAmigoLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaCadastroDeAmigoLayout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(B_Registrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_Voltar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaCadastroDeAmigoLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Telefone)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaCadastroDeAmigoLayout.createSequentialGroup()
                                    .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)))
                            .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TelaCadastroDeAmigoLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TelaCadastroDeAmigoLayout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(txtNomeAmigo)))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        TelaCadastroDeAmigoLayout.setVerticalGroup(
            TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroDeAmigoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(txtNomeAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addGap(29, 29, 29)
                .addGroup(TelaCadastroDeAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Registrar)
                    .addComponent(B_Voltar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaCadastroDeAmigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaCadastroDeAmigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAmigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAmigoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void B_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_VoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_B_VoltarActionPerformed

    private void B_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistrarActionPerformed
        try {

            String nome = "", telefone = "", email = "";
            int id = 0;

            nome = this.txtNomeAmigo.getText();
            telefone = this.txtTelefone.getText();
            email = this.txtEmail.getText();

            if (nome.length() < 3) {
                throw new MensagensException("Preencha um nome valido");
            }

            if (!telefone.matches("\\d{11}")) {
                throw new MensagensException("Insira um telefone valido com DDD");
            }

            if (!email.contains("@") || !email.contains(".com")) {
                throw new MensagensException("Insira um endereço de email válido.");
            }

            ArrayList<Amigo> listaAmigo = objetoamigo.getMinhaLista();

            for (Amigo amigo : listaAmigo) {
                if (amigo.getTelefone().equals(telefone)) {
                    throw new MensagensException("O telefone já está cadastrado.");
                }
                if (amigo.getEmail().equals(email)) {
                    throw new MensagensException("O email já está cadastrado.");
                }
            }

            this.objetoamigo.InsertAmigoBD(id, nome, telefone, email);

            this.txtNomeAmigo.setText("");
            this.txtTelefone.setText("");
            this.txtEmail.setText("");
            JOptionPane.showMessageDialog(rootPane, "Amigo cadastrado com sucesso");
            System.out.println(this.objetoamigo.getMinhaLista().toString());

        } catch (MensagensException erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        } catch (SQLException erro) {
        }


    }//GEN-LAST:event_B_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Registrar;
    private javax.swing.JButton B_Voltar;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Nome;
    private javax.swing.JPanel TelaCadastroDeAmigo;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeAmigo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
